resourcePackages:
  - io.baris.petclinic.springjersey
prettyPrint: true
cacheTTL: 0
openAPI:
  info:
    version: '1.0'
    title: Pet Clinic
    description: Pet Clinic with Spring and Jersey
    termsOfService: https://baris.io/terms/
    contact:
      email: basaran.baris@gmail.com
    license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
